import React, { useState, useRef, useEffect } from 'react';
import { Download, FileSpreadsheet, FileText, ChevronDown, CheckCircle, Loader } from 'lucide-react';
import { API_BASE } from '../config';

/**
 * ExportButton — A dropdown export component for Excel & CSV downloads.
 *
 * Props:
 *  - reportType    : string  — matches the export endpoint (daily|student|faculty|class|subject|monthly|semester|individual)
 *  - filters       : object  — key/value pairs to append as query params
 *  - hasData       : bool    — disables button when no report data is loaded
 *  - user          : object  — { token } for Authorization header
 *  - adminName     : string  — passed to backend for "Generated By" field
 */
const ExportButton = ({ reportType, filters = {}, hasData, user, adminName }) => {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(null); // 'excel' | 'csv' | null
  const [success, setSuccess] = useState(null); // 'excel' | 'csv' | null
  const dropdownRef = useRef(null);

  // Close dropdown on outside click
  useEffect(() => {
    const handler = (e) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
        setOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const buildQueryString = (format) => {
    const params = new URLSearchParams();
    params.set('format', format);
    Object.entries(filters).forEach(([k, v]) => {
      if (v !== undefined && v !== null && v !== '') params.set(k, v);
    });
    return params.toString();
  };

  const handleDownload = async (format) => {
    if (!hasData || loading) return;
    setLoading(format);
    setSuccess(null);
    setOpen(false);

    try {
      const qs = buildQueryString(format);
      const endpoint = `${API_BASE}/api/export/${reportType}?${qs}`;
      const res = await fetch(endpoint, {
        headers: { Authorization: `Bearer ${user?.token}` }
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({ message: 'Export failed.' }));
        throw new Error(err.message || 'Export failed.');
      }

      // Extract filename from Content-Disposition header
      const disposition = res.headers.get('Content-Disposition') || '';
      const filenameMatch = disposition.match(/filename="?([^"]+)"?/);
      const filename = filenameMatch ? filenameMatch[1] : `report.${format === 'excel' ? 'xlsx' : 'csv'}`;

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setSuccess(format);
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      console.error('[ExportButton]', err);
      // Show a simple browser alert for errors
      alert(`Export failed: ${err.message}`);
    } finally {
      setLoading(null);
    }
  };

  const isLoading = loading !== null;

  return (
    <div className="export-btn-wrap" ref={dropdownRef}>
      <button
        type="button"
        className={`btn btn-export ${!hasData ? 'btn-export-disabled' : ''}`}
        disabled={!hasData || isLoading}
        onClick={() => !isLoading && setOpen(prev => !prev)}
        title={!hasData ? 'Generate a report first to enable export' : 'Export data'}
        style={{ height: '40px' }}
      >
        {isLoading ? (
          <>
            <Loader size={14} className="export-spin" />
            <span>Generating…</span>
          </>
        ) : success ? (
          <>
            <CheckCircle size={14} style={{ color: '#22c55e' }} />
            <span style={{ color: '#22c55e' }}>Downloaded!</span>
          </>
        ) : (
          <>
            <Download size={14} />
            <span>Export</span>
            <ChevronDown size={12} className={`export-chevron ${open ? 'open' : ''}`} />
          </>
        )}
      </button>

      {open && !isLoading && (
        <div className="export-dropdown-menu animate-fade">
          <button
            type="button"
            className="export-menu-item"
            onClick={() => handleDownload('excel')}
          >
            <FileSpreadsheet size={15} style={{ color: '#16a34a' }} />
            <div>
              <div className="export-menu-item-title">Download Excel (.xlsx)</div>
              <div className="export-menu-item-desc">Formatted with headers, borders & summary</div>
            </div>
          </button>

          <div className="export-menu-divider" />

          <button
            type="button"
            className="export-menu-item"
            onClick={() => handleDownload('csv')}
          >
            <FileText size={15} style={{ color: '#2563eb' }} />
            <div>
              <div className="export-menu-item-title">Download CSV (.csv)</div>
              <div className="export-menu-item-desc">Compatible with Excel, Sheets & LibreOffice</div>
            </div>
          </button>
        </div>
      )}
    </div>
  );
};

export default ExportButton;
